name: Develop Branch

on:
  push:
    branches:
      - 'develop'

jobs:

  test:
    name: All microservices pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11.x'
      - name: checkstyle
        run: mvn checkstyle:check
      - name: Run backend test
        run: mvnw clean verify -Ddockerfile.skip
      - name: Package application
        run: mvn -B clean package -DskipTests -Ddockerfile.skip
